doctrine_migrations:
    migrations_paths:
        ***REMOVED*** namespace is arbitrary but should be different from App\Migrations
        ***REMOVED*** as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
