framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            ***REMOVED*** use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
