webpack_encore:
    ***REMOVED*** The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
    ***REMOVED*** If multiple builds are defined (as shown below), you can disable the default build:
    ***REMOVED*** output_path: false

    ***REMOVED*** Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
        ***REMOVED*** Uncomment (also under link_attributes) if using Turbo Drive
        ***REMOVED*** https://turbo.hotwired.dev/handbook/drive***REMOVED***reloading-when-assets-change
        ***REMOVED*** 'data-turbo-track': reload
    ***REMOVED*** link_attributes:
        ***REMOVED*** Uncomment if using Turbo Drive
        ***REMOVED*** 'data-turbo-track': reload

    ***REMOVED*** If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    ***REMOVED*** crossorigin: 'anonymous'

    ***REMOVED*** Preload all rendered script and link tags automatically via the HTTP/2 Link header
    ***REMOVED*** preload: true

    ***REMOVED*** Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    ***REMOVED*** strict_mode: false

    ***REMOVED*** If you have multiple builds:
    ***REMOVED*** builds:
        ***REMOVED*** frontend: '%kernel.project_dir%/public/frontend/build'

        ***REMOVED*** pass the build name as the 3rd argument to the Twig functions
        ***REMOVED*** {{ encore_entry_script_tags('entry1', null, 'frontend') }}

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

***REMOVED***when@prod:
***REMOVED***    webpack_encore:
***REMOVED***        ***REMOVED*** Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
***REMOVED***        ***REMOVED*** Available in version 1.2
***REMOVED***        cache: true

***REMOVED***when@test:
***REMOVED***    webpack_encore:
***REMOVED***        strict_mode: false
